version: 0.0
os: linux
hooks:
  ApplicationStart:
    - location: activator start
      timeout: 300
      runas: root
  ApplicationStop:
    - location: activator stop
      timeout: 300
      runas: root
